### ISSUE TITLE
Add "yet another" of the three original games into the refactored version (COMPLETE FOR GOMOKU)

### ISSUE THREAD

**Issue by pconrad** [UCSB-CS56-Projects/cs56-games-client-server-v2#3]
Add either chess, or gomoku. The FIRST game to get added, with GOOD TRUE CLEAN separation of MVC.

Each game gets 300 points, totaling up to 600 possible at maximum.

Refer to this project to find the old source code for chess and gomoku https://github.com/UCSB-CS56-Projects/cs56-games-client-server and use the new MVC setup with this project when re-implementing it.

~estimated 300/game

**Comment by jalexanderqed** [comment]
This issue will be closed once Gomoku is complete. The issue for chess is #9. These may be completed in any order; the separation is just for administrative purposes.

**Comment by jalexanderqed** [comment]
F16 OK (300 pts)
