### ISSUE TITLE
Add descriptions to build.xml

### ISSUE THREAD

**Issue by dcoffill** [UCSB-CS56-Projects/cs56-games-client-server-v2#5]
Due to a lack of description attributes in the build.xml targets, `ant -p` only returns one target.  Add `description` attributes to the targets in build.xml so `ant -p` will list the several useful attributes needed to build, run, and package the client and server.

~Estimated 50

**Comment by jalexanderqed** [comment]
F16 OK (50 pts)

**Comment by davidroster** [comment]
We completed this one by adding all build descriptions. Shows all targets when typing in "ant -p"
