### ISSUE TITLE
Better README.md documentation

### ISSUE THREAD

**Issue by dcoffill** [UCSB-CS56-Projects/cs56-games-client-server-v2#6]
The README has little information on what this program does or how to use it.  Add screenshots, comprehensive instructions for users to build and run the software, and developer documentation to help introduce future developers to the project.

Estimated: ~150 points

**Comment by jalexanderqed** [comment]
Your documentation should include that this is a continuation of https://github.com/UCSB-CS56-Projects/cs56-games-client-server and explain the current state of the project in terms of both functionality and ongoing internal development.

**Comment by jalexanderqed** [comment]
F16 OK (100 pts)
